export const KEYS_TRANSLATIONS = Object.freeze({
  title: 'titulo',
  edition: 'edicion',
  volume: 'volumen',
  isbn: 'isbn',
  publishYear: 'anioPublicacion',
  productionYear: 'anioProduccion',
  filePath: 'urlArchivo',
  fileSize: 'tamanioFichero',
  recipients: 'destinatarios',
  duration: 'duracion',
  resume: 'resumen',
  author: 'autor',
  textPart: 'parteTexto',
  accessibleFormatId: 'formatoAccesibleId',
  publisher: 'editorial',
  languageCode: 'idiomaCodigo',
  observations: 'observaciones',
  userId: 'usuarioId',
  date: 'fecha',
  requestStateId: 'estadoSolicitudId',
  stateDate: 'fechaEstado',
  stateNote: 'notaEstado',
});
